SELECT * FROM titles
WHERE TITLE <> 'STAFF';

SELECT * FROM titles
WHERE TITLE != 'STAFF';

#

SELECT * FROM titles
WHERE EMP_NO = 10007;

SELECT * FROM titles
WHERE TITLE IN (
	SELECT * FROM titles
WHERE EMP_NO = 10007
);

SELECT * FROM titles
WHERE TITLE IN ( 'SENIOR STAFF', 'STAFF' );

#

SELECT * FROM employees 
WHERE GENDER = 'F' 
AND FIRST_NAME LIKE 'S%'
AND HIRE_DATE >= 19900101 ;

SELECT * FROM employees 
WHERE GENDER = 'F' 
AND FIRST_NAME LIKE 'S%'
AND HIRE_DATE >= '1990-01-01' ;

#

USE JAVA;

INSERT INTO MEMBERTBL 
( MEMBERID, MEMBERNAME, MEMBERADDRESS )
VALUES 
( 'KANG', '강성헌', '대구 달서구 용산동' );

SELECT * FROM MEMBERTBL;

#

USE JAVA;

CREATE TABLE TESTTBL2 (
	ID INT AUTO_INCREMENT,
	USERNAME CHAR(3),
	AGE INT,
	PRIMARY KEY(ID)
);

/*
CREATE TABLE TESTTBL3 (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME CHAR(3) PRIMARY KEY,
	AGE INT
);
*/

INSERT INTO TESTTBL2
( USERNAME, AGE)
VALUES
('지민', 25),
('유나', 22),
('유경', 21);

INSERT INTO TESTTBL2
( USERNAME, AGE)
SELECT USERNAME, AGE FROM TESTTBL2;

SELECT USERNAME, 30 FROM TESTTBL2;

INSERT INTO TESTTBL2
( USERNAME, AGE)
SELECT USERNAME, 30 FROM TESTTBL2;
FROM TESTTBL2;

INSERT INTO TESTTBL2
(USERNAME, AGE)
SELECT '홍길동', AGE
FROM TESTTBL2
LIMIT 2;

SELECT AGE, AGE + 10 AS AGEPLUS10, 1 + 1 AS NUM2 FROM TESTTBL2;

#

UPDATE testtbl2 
SET USERNAME = '장현진'
, AGE = 26   
WHERE ID = 3;

#

DELETE FROM testtbl2
WHERE ID = 10;

#

CREATE TABLE TESTTBL3
AS
SELECT * FROM TESTTBL2;

CREATE TABLE TESTTBL4 (SELECT * FROM testtbl2);

#

DROP TABLE testtbl2;
DELETE FROM testtbl3;
TRUNCATE testtbl4;

#

INSERT INTO testtbl3
(ID, USERNAME, AGE) VALUES (1, '지민', 25);

INSERT INTO testtbl3
(ID, USERNAME, AGE) VALUES (1, '유나', 22);

INSERT INTO testtbl3
(ID, USERNAME, AGE) VALUES (3, '유경', 21);


INSERT IGNORE INTO testtbl3
(ID, USERNAME, AGE) VALUES (1, '지민', 25);

INSERT IGNORE INTO testtbl3
(ID, USERNAME, AGE) VALUES (1, '유나', 22);

INSERT IGNORE INTO testtbl3
(ID, USERNAME, AGE) VALUES (3, '유경', 21);

#

SELECT NOW();

SELECT CAST('2021-04-16 12:21:58' AS DATE) AS D_DATE;

SELECT CAST('2021-04-16 12:21:58' AS DATETIME) AS D_DATETIME;

SELECT CAST ('10' AS INT), '10';

SELECT CAST ('10' AS INT), 'A10' + '10', CONCAT('10', '10', '10'), 'AAA' + 'BBB';

SELECT CAST ('10' AS INT) + 10, '10' + '10';

SELECT DATE_FORMAT(NOW(), '%y년 %m월 %d일');

SELECT DATE_FORMAT(NOW(), '%m - %y - %d');

SELECT DATE_FORMAT('2021-04-16 12:21:58', '%y년 %m월 %d일');

SELECT DATE_FORMAT(NOW(), '%Y년 %M월 %D일');

#

USE EMPLOYEES;

SELECT EMP_NO, GENDER,
IF(GENDER='M', '남성', '여성') AS KOREAN_GENDER
FROM EMPLOYEES;

SELECT EMP_NO, GENDER
, CASE WHEN GENDER = 'M'
			THEN '남성'
			ELSE '여성'
	END
FROM EMPLOYEES;

SELECT * FROM SALARIES
WHERE SALARY IS NULL;

SELECT * , IFNULL(SALARY, 'NULL이당')
FROM SALARIES
WHERE SALARY IS NULL OR EMP_NO = 17170;

#

SELECT
	CASE 10
	WHEN 1 THEN '일'
	WHEN 5 THEN '오'
	WHEN 10 THEN '십'
	ELSE '뭐지'
	END AS c_case;
	
#

USE JAVA;

SELECT COMPANY, 
	CASE COMPANY
		WHEN '대우' THEN '탱크대우'
		WHEN 'LG' THEN '사랑해요 LG'
		WHEN '삼성' THEN '또 하나의 가족'
		ELSE '바보'
	END AS addment FROM PRODUCTTBL;
	
#

/*
SELECT *
CASE SALARY 
WHEN >= 70000 THEN '고급인력'
ELSE '저급인력'
FROM SALARIES;
*/

USE EMPLOYEES;

SELECT *,
	CASE WHEN SALARY >= 70000 THEN '고급인력'
	ELSE '저급인력'
	END
FROM SALARIES; 

SELECT *,
	CASE 
		WHEN SALARY >= 80000 THEN '최고급인력'
		WHEN SALARY >= 70000 THEN '고급인력'
	ELSE '저급인력'
	END AS POSITION
FROM SALARIES; 

#

SELECT *
, CONCAT(FIRST_NAME, ' ', LAST_NAME, ' ', GENDER) AS NAME1
, CONCAT_WS(' ', FIRST_NAME, LAST_NAME, GENDER) AS NAME2
, CONCAT_WS(', ', FIRST_NAME, LAST_NAME, GENDER) AS NAME3
FROM EMPLOYEES;

#

SELECT FORMAT(9123456.123456789, 0);

SELECT FORMAT(9123456.123456789, 1);

SELECT FORMAT(9123456.123456789, 2);

SELECT FORMAT(9123456.123456789, 3);

SELECT FORMAT(9123456.123456789, 4);

SELECT FORMAT(36500, 0);

SELECT FORMAT(36500, 1);

SELECT FORMAT(36500, 2);

#

SELECT * , INSERT(DEPT_NO, 2, 2, 'I')
FROM DEPT_EMP;

SELECT * , INSERT(DEPT_NO, 2, 0, 'I')
FROM DEPT_EMP;

#

SELECT *
, UPPER(LEFT(FIRST_NAME, 2))
, LOWER(RIGHT(FIRST_NAME, 3))
FROM EMPLOYEES;

SELECT 
FIRST_NAME
, LPAD(FIRST_NAME, 10, '#')
, RPAD(FIRST_NAME, 10, '#')
FROM EMPLOYEES;

SELECT TRIM('     안녕          ') AS HI
, TRIM('    하   하하          ') AS SMILE
, REPLACE('    하   하하          ', ' ', '');

SELECT BIRTH_DATE, 
LEFT(BIRTH_DATE, 4)
FROM EMPLOYEES;

SELECT BIRTH_DATE, 
LEFT(BIRTH_DATE, 4) AS YEAR,
RIGHT(BIRTH_DATE, 2) AS DAY,
CAST(RIGHT(BIRTH_DATE, 2) AS INT) AS DAY_INT,
SUBSTRING(BIRTH_DATE, 6, 2) AS MONTH,
CAST(SUBSTRING(BIRTH_DATE, 6, 2) AS INT) AS MONTH_INT
FROM EMPLOYEES; 

SELECT 
CEIL(10.0),
CEIL(10.1),
ROUND(10.4),
ROUND(10.5),
FLOOR(10.9),
FLOOR(10.0);
